services:
    sb_words_filter.filter:
        class: SB\WordsFilterBundle\Controller\SBWordsFilterController
#    sb_words_filter.example:
#        class: SB\WordsFilterBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
