<?php

namespace SB\GroupBundle\Repository;

/**
 * GroupCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
