<?php

namespace SB\GroupBundle\Repository;

/**
 * ScribvsGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScribvsGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
